from typing import List, Literal, Optional

from pydantic import BaseModel, Field

from gigachat.models.base import APIResponse
from gigachat.models.chat import Function


class AICheckResult(BaseModel):
    """AI content check result."""

    category: Literal["ai", "human", "mixed"] = Field(description="Classification category: 'ai', 'human', or 'mixed'.")
    characters: int = Field(description="Number of characters in the text.")
    tokens: int = Field(description="Number of tokens in the text.")
    ai_intervals: Optional[List[List[int]]] = Field(
        default=None, description="Text intervals generated by AI. List of [start, end] character indices."
    )


class BalanceValue(BaseModel):
    """Balance entry."""

    usage: str = Field(description="Service usage name.")
    value: float = Field(description="Amount of available units (e.g. tokens).")


class Balance(APIResponse):
    """Balance response."""

    balance: List[BalanceValue] = Field(description="List of balance entries.")


class TokensCount(APIResponse):
    """Token count information."""

    tokens: int = Field(description="Number of tokens.")
    characters: int = Field(description="Number of characters.")
    object_: str = Field(alias="object", description="Object type.")


class OpenApiFunctions(APIResponse):
    """Functions converted from OpenAPI."""

    functions: List[Function] = Field(description="List of converted functions.")


class FunctionValidationIssue(BaseModel):
    """Validation issue for a function schema."""

    description: str = Field(description="Description of the validation issue.")
    schema_location: str = Field(description="Schema location related to the issue.")


class FunctionValidationResult(APIResponse):
    """Function validation response."""

    status: int = Field(description="HTTP-like status code of validation result.")
    message: Literal["Function is valid", "Incorrect function syntax"] = Field(description="Validation result message.")
    json_ai_rules_version: Optional[str] = Field(
        default=None,
        description="Version of validation rules used for JSON-based function validation.",
    )
    errors: Optional[List[FunctionValidationIssue]] = Field(
        default=None,
        description="Validation errors. Present when function syntax is invalid.",
    )
    warnings: Optional[List[FunctionValidationIssue]] = Field(
        default=None,
        description="Validation warnings. Present when the function is valid with non-critical issues.",
    )
