from typing import List, Literal, Optional

from pydantic import BaseModel, Field

from gigachat.models.chat import Function
from gigachat.models.utils import WithXHeaders


class AICheckResult(BaseModel):
    """AI content check result."""

    category: Literal["ai", "human", "mixed"]
    """Classification category: 'ai', 'human', or 'mixed'."""
    characters: int
    """Number of characters in the text."""
    tokens: int
    """Number of tokens in the text."""
    ai_intervals: Optional[List[List[int]]]
    """
    Text intervals generated by AI.
    List of [start, end] character indices.
    """


class BalanceValue(BaseModel):
    """Balance entry."""

    usage: str
    """Service usage name."""
    value: float
    """Amount of available units (e.g. tokens)."""


class Balance(WithXHeaders):
    """Balance response."""

    balance: List[BalanceValue]
    """List of balance entries."""


class TokensCount(WithXHeaders):
    """Token count information."""

    tokens: int
    """Number of tokens."""
    characters: int
    """Number of characters."""
    object_: str = Field(alias="object")
    """Object type."""


class OpenApiFunctions(WithXHeaders):
    """Functions converted from OpenAPI."""

    functions: List[Function]
    """List of converted functions."""
