MAX_CLIENT_EVENT_FRAME_SIZE = 4 * 1024 * 1024
DEFAULT_PCM16_SAMPLE_RATE = 16000
DEFAULT_PCM16_CHANNELS = 1
DEFAULT_MAX_AUDIO_CHUNK_SECONDS = 2.0

__all__ = (
    "DEFAULT_MAX_AUDIO_CHUNK_SECONDS",
    "DEFAULT_PCM16_CHANNELS",
    "DEFAULT_PCM16_SAMPLE_RATE",
    "MAX_CLIENT_EVENT_FRAME_SIZE",
)
