from typing import TYPE_CHECKING

from gigachat.api import tools
from gigachat.authentication import _awith_auth, _with_auth
from gigachat.models.tools import AICheckResult
from gigachat.retry import _awith_retry, _with_retry

if TYPE_CHECKING:
    from gigachat.client import GigaChatAsyncClient, GigaChatSyncClient


class AICheckSyncResource:
    def __init__(self, base_client: "GigaChatSyncClient"):
        self._base_client = base_client

    @_with_retry
    @_with_auth
    def check(self, text: str, model: str) -> AICheckResult:
        """Check the provided text for content generated by AI models."""
        return tools.ai_check_sync(
            self._base_client._client,
            input_=text,
            model=model,
            access_token=self._base_client.token,
        )


class AICheckAsyncResource:
    def __init__(self, base_client: "GigaChatAsyncClient"):
        self._base_client = base_client

    @_awith_retry
    @_awith_auth
    async def check(self, text: str, model: str) -> AICheckResult:
        """Check the provided text for content generated by AI models."""
        return await tools.ai_check_async(
            self._base_client._aclient,
            input_=text,
            model=model,
            access_token=self._base_client.token,
        )
